/* === Données portfolio Jules Le Gars =================================
   Contenu réel — CV 2026 + SAÉ Semestre 1 (BUT GCCD)
   ==================================================================== */

const NAV_SECTIONS = [
  { id: 'accueil',    num: '01', label: 'Accueil' },
  { id: 'cv',         num: '02', label: 'Parcours' },
  { id: 'sae',        num: '03', label: 'SAÉ' },
  { id: 'entreprise', num: '04', label: 'Entreprise' },
  { id: 'contact',    num: '05', label: 'Contact' },
];

const ETUDES = [
  {
    year: '2026 → présent',
    title: 'Cycle Ingénieur ESB',
    place: 'École Supérieure du Bois, Nantes — parcours Conception Bois',
    desc: "Cycle ingénieur orienté conception et dimensionnement de structures bois, construction durable et résistance des matériaux. Une suite naturelle au BUT, vers une expertise plus pointue.",
    tags: ['Conception bois', 'RDM', 'Construction durable'],
  },
  {
    year: '2024 → 2026',
    title: 'BUT Génie Civil & Construction Durable',
    place: 'IUT de Saint-Nazaire — en alternance',
    desc: "Dimensionnement, topographie, mécanique des structures, matériaux, gestion de chantier, diagnostic. Une formation pensée pour le concret, validée en alternance.",
    tags: ['Structures', 'Topographie', 'Matériaux', 'Chantier'],
  },
  {
    year: '2023 → 2024',
    title: 'Classe Préparatoire PTSI',
    place: 'Lycée Livet, Nantes',
    desc: "Année dense en physique, mathématiques et sciences de l'ingénieur. Une étape exigeante qui a confirmé mon attrait pour le concret.",
    tags: ['Maths', 'Physique', 'Sc. Ingénieur'],
  },
  {
    year: '2019 → 2023',
    title: 'Baccalauréat Général',
    place: 'Lycée Livet — spécialités Maths & Sciences de l\'Ingénieur',
    desc: "Bases solides en raisonnement, modélisation et méthode. Premières rencontres avec la conception.",
    tags: ['Maths', 'SI'],
  },
  {
    year: '2015 → 2017',
    title: 'Découverte de l\'artisanat',
    place: 'Association L\'Outil en Main',
    desc: "Initiation à l'ébénisterie, à la charpenterie et au travail du bois. Le premier contact avec la matière, dont j'ai gardé le goût.",
    tags: ['Ébénisterie', 'Charpenterie'],
  },
];

const EXPERIENCES = [
  {
    year: '2024 → présent',
    title: 'Technicien · Projeteur (alternance)',
    place: 'SIXENSE Engineering, Vertou',
    desc: "Préparation des interventions sur ouvrages existants : supports de relevés AutoCAD, inspections, diagnostics — relevés géométriques, pathologies, prélèvements, carottages, essais de corrosimétrie. Au bureau : report DAO, mise au propre des plans, structuration des livrables.",
    tags: ['Diagnostic', 'DAO', 'Auscultation', 'Carottage'],
  },
  {
    year: '2025',
    title: 'Réalisation — outil de suivi',
    place: 'SIXENSE Engineering · projet interne',
    desc: "Développement d'un outil Excel/VBA pour le suivi d'une flotte de capteurs d'analyse matériaux et structures : bilan du parc actif, chiffrage des remises en œuvre à échéance, visualisations.",
    tags: ['Excel', 'VBA', 'Outil interne'],
  },
];

const COMPETENCES_LIB = {
  'AC1.1.1': "Décrire les différentes technologies des bâtiments",
  'AC1.1.2': "Analyser des plans et détails techniques",
  'AC1.1.3': "Produire plans, coupes et détails (normes de dessin)",
  'AC2.1':   "Présenter des solutions techniques de TP",
  'AC2.1.b': "Analyser et produire des plans d'ouvrages de TP",
  'AC3.1.1': "Modéliser un élément structurel simple",
  'AC3.1.2': "Calculer charges, réactions et efforts internes",
  'AC4.1':   "Dimensionner des réseaux (AEP, VMC)",
  'AC5.1':   "Organiser un chantier de BTP",
  'AC5.1.b': "Quantitatif, DQE, planning",
  'AC6.1':   "Piloter techniquement un ouvrage dans le temps",
  'AC6.1.b': "Relever, mesurer, diagnostiquer l'existant",
};

const SAE = [
  // — Semestre 1 ——————————————————————————————————
  { num: '1.01', sem: 1,
    title: "Études d'exécution — Le Clos du Prince",
    short: "Lecture de plans et production des plans de fondation et de coffrage de logements collectifs à La Baule.",
    intro: "Le Clos du Prince est un ensemble de 27 logements répartis sur 3 bâtiments (A, B et C) livré fin 2022 à La Baule. À partir du CCTP gros œuvre, des plans architecturaux et du rapport de sol, j'ai produit les plans de fondations et de coffrage du bâtiment B et C, ainsi qu'une note de synthèse sur les ouvrages affectés au lot gros œuvre.",
    competences: [
      { code: 'AC1.1.1', level: 2 },
      { code: 'AC1.1.2', level: 2 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: "Plan de fondation — Bât. C", ext: 'PDF', path: 'uploads/SAE 1.01/1.01 Livrable 1 - Plan de fondation - Bat C.pdf' },
      { name: "Plan de coffrage — Bât. B (R+1)", ext: 'PDF', path: 'uploads/SAE 1.01/1.01 Livrable 2 - Plan de coffrage - Bat B (R+1) .pdf' },
      { name: "Présentation de la SAÉ", ext: 'PDF', path: 'uploads/SAE 1.01/1.01 Présentation de la SAE.pdf' },
    ],
    bilan: "Première vraie immersion dans la production de plans techniques. J'ai compris la rigueur attendue dans la cotation, la lecture des descentes de charges et la coordination entre les pièces écrites et graphiques.",
    previewLabels: ['Fondation', 'Coffrage', 'Synthèse'],
  },
  { num: '1.02', sem: 1,
    title: "Projet d'ouvrage d'art — OH2 Verger",
    short: "Modes opératoires, plan piédroits et fiche de synthèse d'un ouvrage d'art en travaux publics.",
    intro: "Étude d'un ouvrage d'art en travaux publics : à partir du CCTP, j'ai détaillé les modes opératoires du tablier et de la dalle de transition, produit le plan des piédroits et murs en retour, le tableau de commande du matériel et la fiche de synthèse d'analyse des documents techniques.",
    competences: [
      { code: 'AC2.1',   level: 2 },
      { code: 'AC2.1.b', level: 2 },
      { code: 'AC1.1.3', level: 2 },
    ],
    livrables: [
      { name: "Rendu SAÉ 1.02", ext: 'PDF', path: 'uploads/SAE 1.02/1.02 Jules Le Gars - Rendu SAE 1.02.pdf' },
      { name: "Plan OH2 Verger", ext: 'PDF', path: 'uploads/SAE 1.02/1.02 Plan OH2 Verger - Jules Le Gars.pdf' },
      { name: "Fiche de synthèse", ext: 'PDF', path: 'uploads/SAE 1.02/1.02 Objectifs SAE 1.2.pdf' },
    ],
    bilan: "L'ouvrage d'art m'a ouvert au monde des TP : pieux, longrines, traverses, dalles de transition. Une logique différente du bâtiment, où chaque phase de coulage demande une réflexion à part entière.",
    previewLabels: ['Tablier', 'Piédroit', 'Phasage'],
  },
  { num: '1.03', sem: 1,
    title: "Modélisation d'un élément structurel simple",
    short: "Calculs de solives, poutres BLC et poteaux d'un bâtiment à ossature bois — charges, réactions, moments.",
    intro: "Étude du plancher haut du RdC d'un bâtiment à structure bois. Pour chaque famille d'élément (solives type 1 à 4 en C24, poutres en BLC GL24h, poteaux), j'ai calculé les charges reprises, posé le schéma mécanique, déterminé les réactions d'appuis et tracé les diagrammes d'effort tranchant et de moment fléchissant. Vérification de la contrainte au sol sous la fondation du poteau P1.",
    competences: [
      { code: 'AC3.1.1', level: 2 },
      { code: 'AC3.1.2', level: 3 },
    ],
    livrables: [
      { name: "Rendu SAÉ 1.03 — note de calcul", ext: 'PDF', path: 'uploads/SAE 1.03/GR E1 Jules LE GARS - RENDU SAE 1.03.pdf' },
    ],
    bilan: "Le moment où la mécanique se met à parler. Voir une poutre en BLC se dimensionner depuis une feuille A4, comparer charge ponctuelle et charge répartie — c'est là que la théorie devient outil.",
    previewLabels: ['Solive', 'Poutre BLC', 'Poteau'],
  },
  { num: '1.04', sem: 1,
    title: "Dimensionnement des réseaux secs & humides",
    short: "AEP et VMC d'un immeuble collectif de 13 logements : installations terminales, colonne montante, conduits.",
    intro: "Dimensionnement des réseaux de fluides d'un immeuble de 13 logements (11 appartements + 2 duplex). Volet eau potable : installations terminales de l'appartement 203 et colonne montante. Volet ventilation : étude VMC de l'appartement et dimensionnement d'une conduite de ventilation (cas C1). Outils Excel pour les calculs, dessins DAO pour les schémas de principe.",
    competences: [
      { code: 'AC4.1',   level: 2 },
      { code: 'AC1.1.3', level: 2 },
    ],
    livrables: [
      { name: "Rendu — dimensionnement réseaux", ext: 'PDF', path: 'uploads/SAE 1.04/Jules Le Gars - RENDU.pdf' },
      { name: "Calculs AEP & VMC", ext: 'XLSX', path: null },
      { name: "Dessins DAO — schémas", ext: 'PDF', path: null },
    ],
    bilan: "Les réseaux, c'est l'invisible qui fait vivre le bâtiment. Cette SAÉ m'a appris que dimensionner, c'est aussi anticiper le confort, la maintenance et les pertes de charge.",
    previewLabels: ['AEP', 'VMC', 'Schéma'],
  },
  { num: '1.05', sem: 1,
    title: "Devis d'un ouvrage simple — Maison St Julien",
    short: "Quantitatif, DQE et planning des lots maçonnerie, plâtrerie et chape/carrelage d'une maison R+1.",
    intro: "La Maison St Julien est une maison individuelle R+1 de 113 m² construite à St-Julien-de-Concelles. À partir des pièces écrites et graphiques, j'ai identifié les acteurs de l'acte de construire, rédigé une note sur les modes constructifs, et établi le quantitatif maçonnerie, le DQE + commande + planning du lot plâtrerie, puis le mode opératoire, planning et DQE du lot chape et carrelage.",
    competences: [
      { code: 'AC5.1',   level: 2 },
      { code: 'AC5.1.b', level: 3 },
    ],
    livrables: [
      { name: "Compte rendu SAÉ 1.05", ext: 'PDF', path: 'uploads/SAE 1.05/Compte rendu SAÉ 1.05 - Jules Le Gars.pdf' },
      { name: "Chiffrage lot plâtrerie", ext: 'XLSX', path: 'uploads/SAE 1.05/ANNEXE 2 Chiffrage lot plâtrerie.xlsx' },
      { name: "Chiffrage chape & carrelage", ext: 'XLSX', path: 'uploads/SAE 1.05/ANNEXE 3 Chiffrage Lot chape & Carrelage.xlsx' },
    ],
    bilan: "Chiffrer, c'est comprendre comment un bâtiment est réellement fait — tâche par tâche, mètre carré par mètre carré. Cette SAÉ m'a appris la valeur du temps et la mécanique d'une opération.",
    previewLabels: ['Quantitatif', 'DQE', 'Planning'],
  },
  { num: '1.06', sem: 1,
    title: "État des lieux d'un ouvrage existant",
    short: "Relevé, dossier de plans et mesures (acoustique, thermique, hygrométrie) d'une salle de TD à l'IUT.",
    intro: "Mission de maîtrise d'œuvre pour l'Université de Nantes : relevé d'une salle de TD à l'IUT en vue d'une rénovation. J'ai constitué le dossier de plans (vue en plan, coupes, détails), réalisé un rapport photographique de l'existant, dressé le tableau d'état des ouvrages, et effectué les mesures acoustiques, thermiques et hygrométriques pour vérifier la conformité réglementaire.",
    competences: [
      { code: 'AC6.1',   level: 2 },
      { code: 'AC6.1.b', level: 3 },
      { code: 'AC1.1.3', level: 2 },
    ],
    livrables: [
      { name: "Rapport d'état des lieux", ext: 'PDF', path: 'uploads/SAE 1.06/Jules Le Gars - Rapport SAE 1.06.pdf' },
      { name: "Dossier de plans", ext: 'PDF', path: null },
      { name: "Mesures (acou./therm./hygro.)", ext: 'PDF', path: null },
    ],
    bilan: "Cette SAÉ a déclenché ce qui est devenu mon axe pro chez SIXENSE : ausculter l'existant, le mesurer, comprendre comment il vit. Un travail patient et méticuleux que j'aime particulièrement.",
    previewLabels: ['Relevé', 'Plans', 'Mesures'],
  },
  // — Semestre 2 (placeholders en attendant le contenu réel) ——————————————
  { num: '2.01', sem: 2,
    title: "Projet d'aménagement de bâtiment — Donges",
    short: "Conception de l'aménagement d'une cellule artisanale dans un programme de 3 bâtiments à Donges.",
    intro: "Programme de 3 bâtiments à usage commercial / artisanal / stockage livrés bruts. À partir du CCTP, étude de la couverture, de l'étanchéité et dimensionnement de l'évacuation des eaux pluviales du bâtiment B. Puis projet d'aménagement de la cellule A9 (plans, descriptif sommaire et estimatif).",
    competences: [
      { code: 'AC1.1.1', level: 3 },
      { code: 'AC1.1.2', level: 3 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: "Rapport d'étude SAÉ 2.01", ext: 'PDF', path: "uploads/SAE 2.01/Rapport d'étude SAE 2.01 - LE GARS_RAULT_HEGRON_FAGOUR.pdf" },
      { name: "Tracé — aménagement A9", ext: 'PDF', path: 'uploads/SAE 2.01/TRACÉ.pdf' },
    ],
    bilan: "Première vraie SAÉ de conception complète : passer de la cellule brute à un espace utile. J'ai aimé arbitrer entre programme, contraintes et budget.",
    previewLabels: ['Couverture', 'EP', 'Aménagement'],
  },
  { num: '2.02', sem: 2,
    title: "Topographie — implantation",
    short: "À compléter — implantation d'ouvrage sur site, tolérances et report.",
    intro: "Contenu à compléter après le rendu de cette SAÉ.",
    competences: [
      { code: 'AC1.1.3', level: 2 },
    ],
    livrables: [
      { name: "Livrable — à venir", ext: 'PDF' },
    ],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'],
  },
  { num: '2.03', sem: 2,
    title: "Dimensionnement avancé",
    short: "À compléter — structure complète, fondations sur sol hétérogène.",
    intro: "Contenu à compléter après le rendu de cette SAÉ.",
    competences: [
      { code: 'AC3.1.2', level: 3 },
    ],
    livrables: [
      { name: "Livrable — à venir", ext: 'PDF' },
    ],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'],
  },
  { num: '2.04', sem: 2,
    title: "Diagnostic d'ouvrage existant",
    short: "À compléter — auscultation, pathologies, scénarios de réhabilitation.",
    intro: "Contenu à compléter après le rendu de cette SAÉ.",
    competences: [
      { code: 'AC6.1',   level: 3 },
      { code: 'AC6.1.b', level: 3 },
    ],
    livrables: [
      { name: "Livrable — à venir", ext: 'PDF' },
    ],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'],
  },
  { num: '2.05', sem: 2,
    title: "Suivi d'un chantier",
    short: "À compléter — comptes-rendus, contrôle qualité, photothèque.",
    intro: "Contenu à compléter après le rendu de cette SAÉ.",
    competences: [
      { code: 'AC5.1', level: 3 },
    ],
    livrables: [
      { name: "Livrable — à venir", ext: 'PDF' },
    ],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'],
  },
  { num: '2.06', sem: 2,
    title: "Analyse environnementale d'un projet",
    short: "À compléter — ACV simplifiée, choix matériaux bas carbone, biosourcés.",
    intro: "Contenu à compléter après le rendu de cette SAÉ.",
    competences: [
      { code: 'AC1.1.1', level: 2 },
    ],
    livrables: [
      { name: "Livrable — à venir", ext: 'PDF' },
    ],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'],
  },
  // — Semestre 3 (placeholders en attendant les SAÉ) ——————————————
  { num: '3.01', sem: 3, title: "SAÉ 3.01 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 3.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '3.02', sem: 3, title: "SAÉ 3.02 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 3.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '3.03', sem: 3, title: "SAÉ 3.03 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 3.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '3.04', sem: 3, title: "SAÉ 3.04 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 3.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '3.05', sem: 3, title: "SAÉ 3.05 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 3.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '3.06', sem: 3, title: "SAÉ 3.06 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 3.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  // — Semestre 4 (placeholders) ——————————————————————————————————
  { num: '4.01', sem: 4, title: "SAÉ 4.01 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.02', sem: 4, title: "SAÉ 4.02 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.03', sem: 4, title: "SAÉ 4.03 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.04', sem: 4, title: "SAÉ 4.04 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.05', sem: 4, title: "SAÉ 4.05 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.06', sem: 4, title: "SAÉ 4.06 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ n'a pas encore été rendue. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: "Livrable — à venir", ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
];

const COMPANY_PHOTOS = [
  { src: 'assets/carousel-2.jpg', caption: "Accès auscultation — sous tablier" },
  { src: 'assets/carousel-3.jpg', caption: "Inspection détaillée — pont sur la Loire" },
  { src: 'assets/carousel-4.jpg', caption: "Sous-face de tablier — ouvrage routier" },
  { src: 'assets/carousel-5.jpg', caption: "Nacelle d'inspection — équipe SIXENSE" },
  { src: 'assets/carousel-9.jpg', caption: "Engin de visite Barin — déploiement matinal" },
  { src: 'assets/carousel-6.jpg', caption: "Auscultation visuelle — relevé de pathologies" },
  { src: 'assets/carousel-7.jpg', caption: "Inspection d'un viaduc à poutres" },
  { src: 'assets/carousel-8.jpg', caption: "Pont jumeau — circulation maintenue" },
  { src: 'assets/carousel-1.jpg', caption: "Convoi d'inspection en place sur tablier" },
];

Object.assign(window, {
  NAV_SECTIONS, ETUDES, EXPERIENCES, SAE, COMPETENCES_LIB, COMPANY_PHOTOS,
});
