/* === Données portfolio Jules Le Gars =================================
   Contenu réel — CV 2026 + SAÉ Semestres 1–3 (BUT GCCD)
   ==================================================================== */

const NAV_SECTIONS = [
  { id: 'accueil',    num: '01', label: 'Accueil' },
  { id: 'cv',         num: '02', label: 'Parcours' },
  { id: 'sae',        num: '03', label: 'SAÉ' },
  { id: 'entreprise', num: '04', label: 'Entreprise' },
  { id: 'contact',    num: '05', label: 'Contact' },
];

const ETUDES = [
  {
    year: '2026 → présent',
    title: 'Cycle Ingénieur ESB',
    place: 'École Supérieure du Bois, Nantes — parcours Conception Bois',
    desc: "Cycle ingénieur orienté conception et dimensionnement de structures bois, construction durable et résistance des matériaux. Une suite naturelle au BUT, vers une expertise plus pointue.",
    tags: ['Conception bois', 'RDM', 'Construction durable'],
  },
  {
    year: '2024 → 2026',
    title: 'BUT Génie Civil & Construction Durable',
    place: 'IUT de Saint-Nazaire — en alternance',
    desc: "Dimensionnement, topographie, mécanique des structures, matériaux, gestion de chantier, diagnostic. Une formation pensée pour le concret, validée en alternance.",
    tags: ['Structures', 'Topographie', 'Matériaux', 'Chantier'],
  },
  {
    year: '2023 → 2024',
    title: 'Classe Préparatoire PTSI',
    place: 'Lycée Livet, Nantes',
    desc: "Année dense en physique, mathématiques et sciences de l'ingénieur. Une étape exigeante qui a confirmé mon attrait pour le concret.",
    tags: ['Maths', 'Physique', 'Sc. Ingénieur'],
  },
  {
    year: '2019 → 2023',
    title: 'Baccalauréat Général',
    place: 'Lycée Livet — spécialités Maths & Sciences de l\'Ingénieur',
    desc: "Bases solides en raisonnement, modélisation et méthode. Premières rencontres avec la conception.",
    tags: ['Maths', 'SI'],
  },
  {
    year: '2015 → 2017',
    title: 'Découverte de l\'artisanat',
    place: 'Association L\'Outil en Main',
    desc: "Initiation à l'ébénisterie, à la charpenterie et au travail du bois. Le premier contact avec la matière, dont j'ai gardé le goût.",
    tags: ['Ébénisterie', 'Charpenterie'],
  },
];

const EXPERIENCES = [
  {
    year: '2024 → présent',
    title: 'Technicien · Projeteur (alternance)',
    place: 'SIXENSE Engineering, Vertou',
    desc: "Préparation des interventions sur ouvrages existants : supports de relevés AutoCAD, inspections, diagnostics — relevés géométriques, pathologies, prélèvements, carottages, essais de corrosimétrie. Au bureau : report DAO, mise au propre des plans, structuration des livrables.",
    tags: ['Diagnostic', 'DAO', 'Auscultation', 'Carottage'],
  },
  {
    year: '2025',
    title: 'Réalisation — outil de suivi',
    place: 'SIXENSE Engineering · projet interne',
    desc: "Développement d'un outil Excel/VBA pour le suivi d'une flotte de capteurs d'analyse matériaux et structures : bilan du parc actif, chiffrage des remises en œuvre à échéance, visualisations.",
    tags: ['Excel', 'VBA', 'Outil interne'],
  },
];

const COMPETENCES_LIB = {
  'AC1.1.1': "Décrire les différentes technologies des bâtiments",
  'AC1.1.2': "Analyser des plans et détails techniques",
  'AC1.1.3': "Produire plans, coupes et détails (normes de dessin)",
  'AC1.4':   "Conception 3D et DAO d'un espace intérieur",
  'AC1.5':   "Analyse thermique et hygrothermique des parois",
  'AC1.6':   "Analyse du cycle de vie et performance béton",
  'AC1.7':   "Modélisation BIM — Revit Architecture",
  'AC2.1':   "Présenter des solutions techniques de TP",
  'AC2.1.b': "Analyser et produire des plans d'ouvrages de TP",
  'AC2.2':   "Voirie, réseaux divers et terrassement (VRD)",
  'AC2.3':   "Relevé topographique complexe et de façade",
  'AC3.1.1': "Modéliser un élément structurel simple",
  'AC3.1.2': "Calculer charges, réactions et efforts internes",
  'AC3.2':   "Calcul des sollicitations selon les Eurocodes (logiciel)",
  'AC3.3':   "Dimensionnement d'ossature légère bois/métal",
  'AC4.1':   "Dimensionner des réseaux (AEP, VMC)",
  'AC5.1':   "Organiser un chantier de BTP",
  'AC5.1.b': "Quantitatif, DQE, planning",
  'AC5.2':   "Planification de chantier — chemin de fer OA",
  'AC6.1':   "Piloter techniquement un ouvrage dans le temps",
  'AC6.1.b': "Relever, mesurer, diagnostiquer l'existant",
  'AC6.2':   "Diagnostic réglementaire complet d'un bâtiment",
};

const SAE = [
  // — Semestre 1 ——————————————————————————————————
  { num: '1.01', sem: 1,
    title: "Études d'exécution — Le Clos du Prince",
    short: "Lecture de plans et production des plans de fondation et de coffrage de logements collectifs à La Baule.",
    intro: "Le Clos du Prince est un ensemble de 27 logements répartis sur 3 bâtiments (A, B et C) livré fin 2022 à La Baule. À partir du CCTP gros œuvre, des plans architecturaux et du rapport de sol, j'ai produit les plans de fondations et de coffrage des bâtiments B et C, ainsi qu'une note de synthèse sur les ouvrages affectés au lot gros œuvre.",
    competences: [
      { code: 'AC1.1.1', level: 2 },
      { code: 'AC1.1.2', level: 3 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: 'Plan de fondation — Bât. C', ext: 'PDF', path: 'SAE/SAE 1.01/1.01 Livrable 1 - Plan de fondation - Bat C.pdf' },
      { name: 'Plan de coffrage — Bât. B (R+1)', ext: 'PDF', path: 'SAE/SAE 1.01/1.01 Livrable 2 - Plan de coffrage - Bat B (R+1) .pdf' },
    ],
    bilan: "Cette SAÉ était l'occasion de réaliser mes premiers plans de fondation. La lecture du CCTP et son analyse ont été déterminantes dans la réalisation de mon travail ; j'ai donc compris que cette lecture préalable était très importante pour le dessin. Cette expérience me sera vraiment utile pour la suite, surtout en bureau d'études où je passe une grande partie de mon temps à reporter des désordres ou actualiser des plans.",
    previewLabels: ['Fondation Bât. C', 'Coffrage Bât. B', 'Plans DAO'],
  },

  { num: '1.02', sem: 1,
    title: "Projet d'ouvrage d'art — OH2 Verger",
    short: "Modes opératoires, plan piédroit et fiche de synthèse d'un ouvrage d'art en travaux publics.",
    intro: "Étude d'un ouvrage d'art en travaux publics (OH2 du Verger, commune de Seiches-sur-le-Loir, maîtrise d'ouvrage Mairie). À partir du CCTP, j'ai rédigé les modes opératoires détaillés du tablier et de la dalle de transition, produit le plan normé du piédroit EST avec murs en retour, le tableau de commande du coffrage Doka et la fiche de synthèse d'analyse des documents techniques.",
    competences: [
      { code: 'AC2.1',   level: 2 },
      { code: 'AC2.1.b', level: 3 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: 'Compte rendu SAÉ 1.02', ext: 'PDF', path: 'SAE/SAE 1.02/1.02 Jules Le Gars - Rendu SAE 1.02.pdf' },
      { name: 'Plan piédroit EST — OH2 Verger', ext: 'PDF', path: 'SAE/SAE 1.02/1.02 Plan OH2 Verger - Jules Le Gars.pdf' },
    ],
    bilan: "Cette SAÉ m'a permis de comprendre le phasage des travaux de petits ouvrages d'arts, d'améliorer mes compétences en lecture de CCTP. Le travail de dessin m'a aussi permis d'approfondir ma connaissance d'AutoCAD en diversifiant le domaine dans lequel je dessine. Ces savoirs me seront très utiles si je suis amené à faire des plans d'avant-projet ou de phasage en maîtrise d'œuvre chez SIXENSE Engineering.",
    previewLabels: ['Tablier & phasage', 'Plan piédroit EST', 'Coffrage Doka'],
  },

  { num: '1.03', sem: 1,
    title: "Modélisation d'un élément structurel simple",
    short: "Calculs de solives, poutres BLC et poteaux d'un bâtiment à ossature bois — charges, réactions, moments.",
    intro: "Étude du plancher haut du RdC d'un bâtiment à structure bois. Pour chaque famille d'éléments (solives type 1 à 4 en C24, poutres en BLC GL24h, poteaux), j'ai calculé les charges reprises, posé le schéma mécanique, déterminé les réactions d'appuis et tracé les diagrammes d'effort tranchant et de moment fléchissant. Vérification de la contrainte au sol sous la fondation du poteau P1.",
    competences: [
      { code: 'AC3.1.1', level: 2 },
      { code: 'AC3.1.2', level: 3 },
    ],
    livrables: [
      { name: 'Rendu SAÉ 1.03 — note de calcul', ext: 'PDF', path: 'SAE/SAE 1.03/GR E1 Jules LE GARS - RENDU SAE 1.03.pdf' },
    ],
    bilan: "Cette SAÉ était une bonne mise en pratique des cours de MS1 dispensés lors du premier semestre. J'ai apprécié modéliser la structure partie par partie pour arriver à un calcul de pression transmise au sol. L'intérêt d'appliquer des calculs à une situation réaliste est de mieux visualiser la manière dont les charges se transmettent dans une structure, jusqu'au sol. J'ai cependant des progrès à fournir en lecture et analyse de sujet/documents puisque mes valeurs de charges étaient erronées.",
    previewLabels: ['Schéma mécanique', 'Diagrammes N-V-M', 'Note de calcul'],
  },

  { num: '1.04', sem: 1,
    title: "Dimensionnement des réseaux secs & humides",
    short: "AEP et VMC d'un immeuble collectif de 13 logements : installations terminales, colonne montante, conduits.",
    intro: "Dimensionnement des réseaux de fluides d'un immeuble de 13 logements (11 appartements + 2 duplex). Volet eau potable : installations terminales de l'appartement 203 et colonne montante (tronçons A à D). Volet ventilation : étude VMC de l'appartement et dimensionnement d'une conduite de ventilation (cas C1). Calculs sur Excel, schémas DAO pour les plans de principe.",
    competences: [
      { code: 'AC4.1',   level: 3 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: 'Rapport de dimensionnement réseaux', ext: 'PDF', path: 'SAE/SAE 1.04/Jules Le Gars - RENDU.pdf' },
      { name: 'Plans DAO — hydraulique & aéraulique', ext: 'PDF', path: null },
      { name: 'Calculs débits & pertes de charge', ext: 'XLSX', path: null },
    ],
    bilan: "Cette SAÉ était l'occasion d'appliquer les notions travaillées en réseaux secs et humides. J'ai pu me familiariser avec les différents enjeux de la construction urbaine, plus précisément des enjeux d'acheminement et d'évacuation des eaux dans de grands bâtiments. La partie aéraulique était également intéressante puisqu'elle permettait de comprendre le cheminement des systèmes de VMC. Mon appétence pour les logiciels de traitement de données tels qu'Excel a rendu mon travail beaucoup plus efficace que je n'aurais pu l'espérer.",
    previewLabels: ['Réseau AEP', 'Réseau VMC', 'Plans DAO'],
  },

  { num: '1.05', sem: 1,
    title: "Devis d'un ouvrage simple — Maison St Julien",
    short: "Quantitatif, DQE et planning des lots maçonnerie, plâtrerie et chape/carrelage d'une maison R+1.",
    intro: "La Maison St Julien est une maison individuelle R+1 de 113 m² construite à St-Julien-de-Concelles. À partir des pièces écrites et graphiques, j'ai identifié les acteurs de l'acte de construire, rédigé une note sur les modes constructifs, et établi le quantitatif maçonnerie, le DQE + commande + planning du lot plâtrerie (via Batiprix), puis le mode opératoire, planning et DQE du lot chape et carrelage.",
    competences: [
      { code: 'AC5.1',   level: 2 },
      { code: 'AC5.1.b', level: 3 },
    ],
    livrables: [
      { name: 'Compte rendu SAÉ 1.05', ext: 'PDF', path: 'SAE/SAE 1.05/Compte rendu SAÉ 1.05 - Jules Le Gars.pdf' },
      { name: 'Chiffrage lot plâtrerie', ext: 'XLSX', path: 'SAE/SAE 1.05/ANNEXE 2 Chiffrage lot plâtrerie.xlsx' },
      { name: 'Chiffrage chape & carrelage', ext: 'XLSX', path: 'SAE/SAE 1.05/ANNEXE 3 Chiffrage Lot chape & Carrelage.xlsx' },
    ],
    bilan: "Cette SAÉ était une bonne mise en pratique des cours de MGM1 et un exercice intéressant pour réaliser un chiffrage en prenant plusieurs paramètres en compte. C'était également l'occasion de comprendre comment sont établis les prix des différents lots des corps d'état secondaires. L'utilisation de la plateforme Batiprix était utile bien qu'un peu répétitive.",
    previewLabels: ['Quantitatif maçon.', 'DQE plâtrerie', 'Planning chape'],
  },

  { num: '1.06', sem: 1,
    title: "État des lieux d'un ouvrage existant",
    short: "Relevé, dossier de plans et mesures (acoustique, thermique, hygrométrie) d'une salle de TD à l'IUT.",
    intro: "Mission de maîtrise d'œuvre pour l'Université de Nantes : relevé d'une salle de TD à l'IUT en vue d'une rénovation. J'ai constitué le dossier de plans (vue en plan, coupes, détails), réalisé un rapport photographique de l'existant, dressé le tableau d'état des ouvrages, et effectué les mesures acoustiques, thermiques et hygrométriques pour vérifier la conformité réglementaire.",
    competences: [
      { code: 'AC6.1',   level: 2 },
      { code: 'AC6.1.b', level: 3 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: "Rapport d'état des lieux SAÉ 1.06", ext: 'PDF', path: 'SAE/SAE 1.06/Jules Le Gars - Rapport SAE 1.06.pdf' },
      { name: 'Dossier de plans (relevé DAO)', ext: 'PDF', path: null },
      { name: 'Mesures acou. / therm. / hygro.', ext: 'PDF', path: null },
    ],
    bilan: "Cette SAÉ très complète constituait l'application de plusieurs enseignements tels que ceux portant sur le son ou l'étude thermique des bâtiments. Elle a constitué un bon entraînement à la rédaction de contenu scientifique puisqu'elle contient une multitude d'audits et de résultats. Les TP portant sur le son étaient intéressants bien que relativement simples.",
    previewLabels: ['Plans relevés', 'Mesures acoustiques', 'Rapport complet'],
  },

  // — Semestre 2 ——————————————————————————————————
  { num: '2.01', sem: 2,
    title: "Aménagement d'une cellule commerciale — Six Croix, Donges",
    short: "Aménagement d'une cellule cuisiniste à Donges — vues 3D, plans 2D, notice descriptive, chiffrage DQE.",
    intro: "Programme de trois bâtiments commerciaux/artisanaux livrés bruts à l'Espace des Six Croix à Donges (cuisiniste, bureaux, salle VR). En groupe de quatre, j'ai pris en charge la modélisation 3D de la cellule A9 et coordonné la mise en forme du rapport. Livrables : vues 3D détaillées, plans 2D (niveaux, coupes, cellule A9), notice technique des travaux (cloisons, doublage, revêtements, menuiserie), quantitatif et chiffrage DQE/BATIPRIX, documents DAO d'exécution et d'étanchéité.",
    competences: [
      { code: 'AC1.1.1', level: 3 },
      { code: 'AC1.1.3', level: 3 },
      { code: 'AC1.4',   level: 3 },
    ],
    livrables: [
      { name: "Rapport d'étude SAÉ 2.01", ext: 'PDF', path: "SAE/SAE 2.01/Rapport d'étude SAE 2.01 - LE GARS_RAULT_HEGRON_FAGOUR.pdf" },
      { name: 'Tracé — aménagement cellule A9', ext: 'PDF', path: 'SAE/SAE 2.01/TRACÉ.pdf' },
    ],
    bilan: "Cette SAÉ était l'occasion de travailler en groupe de manière plus avancée que sur d'autres projets ; elle requérait de mettre en œuvre nos connaissances en DAO, chiffrage et modélisation 3D pour proposer l'aménagement d'un bâtiment réservé par un cuisiniste. J'ai eu la charge de la partie 3D et de la mise en forme du rapport. L'utilisation d'un logiciel tiers pour la 3D m'a permis d'exprimer ma créativité plus librement que prévu. La coordination d'équipe était primordiale et ce fût une réussite.",
    previewLabels: ['Vues 3D', 'Plans 2D', 'Chiffrage DQE'],
  },

  { num: '2.02', sem: 2,
    title: "Projet VRD — Lotissement La Prinais",
    short: "Projet VRD complet : plan de voirie, profils en long/travers, assainissement et étude de réemploi des matériaux.",
    intro: "Conception complète d'un projet VRD pour le lotissement La Prinais : plan de voirie en plan (1/1000), profils en long et en travers normés, plan d'assainissement eaux usées, calcul des cubatures de terrassement en déblais/remblais sur Excel, et étude des matériaux de réemploi routier. Représentation DAO soignée en binôme avec Briac Rault.",
    competences: [
      { code: 'AC2.1.b', level: 3 },
      { code: 'AC2.2',   level: 3 },
      { code: 'AC5.1.b', level: 2 },
    ],
    livrables: [
      { name: 'Profil en long de la voirie', ext: 'PDF', path: 'SAE/SAE 2.02/Profil en long de la voirie complété - Jules LE GARS.pdf' },
      { name: 'Profil en travers voirie', ext: 'PDF', path: 'SAE/SAE 2.02/Profil en travers voirie complété - Jules LE GARS.pdf' },
      { name: "Plan d'assainissement", ext: 'PDF', path: 'SAE/SAE 2.02/Plan dassainissement complété - Jules LE GARS.pdf' },
      { name: 'Calculs cubatures & réseaux', ext: 'XLSX', path: 'SAE/SAE 2.02/Calculs SAÉ 2.02 - Jules Le Gars.xlsx' },
      { name: 'Étude matériaux de réemploi', ext: 'XLSX', path: 'SAE/SAE 2.02/Etude des matériaux (ID-rémplois-compactage) - Jules Le Gars.xlsx' },
    ],
    bilan: "Cette SAÉ fait suite aux TD effectués en TTP2, elle constitue une application plus complète du cours sur la voirie mais aussi des notions de topographie avec les profils en long et en travers demandés. Ayant pris le temps d'automatiser la méthode avec des feuilles Excel lors des TD de TTP2, j'ai pris nettement moins de temps sur les calculs et ai eu l'occasion de soigner mes tracés. En revanche, j'aurais dû passer plus de temps pour rédiger un document explicatif plutôt que de ne restituer que mes calculs sous forme de tableur.",
    previewLabels: ['Plan voirie', 'Profils long/travers', 'Assainissement'],
  },

  { num: '2.03', sem: 2,
    title: "Relevé complexe — Campus Heinlex",
    short: "Relevé topographique complexe sur le Campus Heinlex — modélisation terrain 3D, plan d'implantation, façade ITE.",
    intro: "Relevé complexe planimétrique et altimétrique sur le Campus Heinlex de l'IUT Saint-Nazaire : modélisation 3D du terrain sous Mensura (deux coupes significatives, quantitatif des déblais), plan d'implantation de la plateforme d'échafaudage et plan de façade à isoler par ITE. Mission réalisée en binôme avec une grande autonomie sur le terrain et en DAO.",
    competences: [
      { code: 'AC6.1.b', level: 3 },
      { code: 'AC2.3',   level: 3 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: 'Rendu SAÉ 2.03 (rapport + annexes)', ext: 'PDF', path: 'SAE/SAE 2.03/contexte/Rendu SAE 2.03 + Annexes - Jules Le Gars.pdf' },
      { name: "Plan d'implantation — plateforme", ext: 'PDF', path: "SAE/SAE 2.03/Plan d'Implantation.pdf" },
      { name: 'Plan de façade — ITE', ext: 'PDF', path: 'SAE/SAE 2.03/FACADE.pdf' },
    ],
    bilan: "Cette SAÉ était une mise en application du savoir-faire acquis en topographie 1 et 2, elle proposait une grande autonomie sur la partie relevés et la partie mise en plan/exploitation des relevés, ce qui était très agréable. Je pense avoir progressé en relevé topographique au cours de cette année en repérant plus simplement les points qui sont les plus cruciaux à relever.",
    previewLabels: ['Terrain 3D Mensura', "Plan d'implantation", 'Façade ITE'],
  },

  { num: '2.04', sem: 2,
    title: "Calcul des sollicitations — structure métallique",
    short: "Calcul des sollicitations et déformations d'une structure métallique selon les Eurocodes avec logiciel dédié.",
    intro: "Calcul des sollicitations et vérifications de déformations d'une structure métallique (le bâtiment de l'Espace Six Croix étudié en SAÉ 2.01) à l'aide d'un logiciel professionnel. Identification des charges, descentes de charges, schémas mécaniques, calculs de moment fléchissant et d'effort tranchant, vérifications ELU et ELS selon les Eurocodes.",
    competences: [
      { code: 'AC3.1.1', level: 3 },
      { code: 'AC3.2',   level: 3 },
    ],
    livrables: [
      { name: 'Note de calcul de structure', ext: 'PDF', path: 'SAE/SAE 2.04/Note de Calcul SAE 2.04 - Jules Le Gars.pdf' },
    ],
    bilan: "Cette SAÉ faisait appel à nos connaissances en mécanique des structures et en lecture de documents, elle fait suite à la SAÉ 1.03 et inclut une démarche de recherche intéressante. La partie la plus intéressante était l'étude de la structure du bâtiment puisqu'elle demandait de faire des hypothèses et de construire le modèle pas à pas. Je pense avoir grandement progressé en rigueur dans ma lecture du sujet et des documents par rapport à la SAÉ 1.03.",
    previewLabels: ['Modèle mécanique', 'Diagrammes M-V', 'Vérif. Eurocode'],
  },

  { num: '2.05', sem: 2,
    title: "Performance d'isolation — contraintes hygrothermiques",
    short: "Analyse hygrothermique des parois — simulation Ubakus, condensation, solutions biosourcées, RE2020.",
    intro: "Étude hygrothermique de trois cas de parois courantes (mur, toiture, plancher bas) à l'aide du logiciel Ubakus. Identification des risques de condensation interstitielle et superficielle, comparaison de solutions d'isolation biosourcées et conventionnelles, vérification des exigences RE2020. Rendu sous forme d'une synthèse de deux pages distillant l'essentiel des analyses.",
    competences: [
      { code: 'AC1.5', level: 3 },
    ],
    livrables: [
      { name: 'Synthèse SAÉ 2.05 (2 pages)', ext: 'PDF', path: 'SAE/SAE 2.05/Synthèse SAÉ 2.05 - Jules Le Gars.pdf' },
    ],
    bilan: "Cette SAÉ était l'occasion de faire un bilan sur mes connaissances en transferts thermiques et hygrométriques, elle propose trois mises en pratique de ces savoirs et demande une rigueur de rédaction plus élevée que dans les autres SAÉ. En effet, synthétiser un travail relativement long et ses conclusions en seulement deux pages demande un travail poussé en rédaction.",
    previewLabels: ['Analyse parois', 'Risques condensation', 'Synthèse RE2020'],
  },

  { num: '2.06', sem: 2,
    title: "Planification de travaux — pont à piles",
    short: "Planification d'un pont à piles : dimensionnement coffrage, chemin de fer, planning Project Libre.",
    intro: "Planification du coulage d'un pont à piles et culées (projet GALAR Ingénierie) : note de calcul des charges sur coffrages et étaiements (vérification ELU/ELS selon les Eurocodes), diagramme en chemin de fer du coulage du béton, et plannings grande maille et d'exécution réalisés sous Project Libre avec optimisation de la courbe de main d'œuvre.",
    competences: [
      { code: 'AC3.1.2', level: 3 },
      { code: 'AC5.2',   level: 3 },
    ],
    livrables: [
      { name: 'Note de calcul — coffrage & étaiement', ext: 'PDF', path: 'SAE/SAE 2.06/Note de calcul - Jules LE GARS.pdf' },
      { name: 'Note de raisonnement — planning grande maille', ext: 'PDF', path: 'SAE/SAE 2.06/Note de raisonnement pour la plannification - Jules Le Gars.pdf' },
      { name: "Note de raisonnement — planning d'exécution", ext: 'PDF', path: "SAE/SAE 2.06/Note de raisonnement pour le planning d'execution - Jules LE GARS.pdf" },
    ],
    bilan: "Cette SAÉ offrait l'occasion d'utiliser une belle panoplie de matières : mécanique des structures, MGM2, TTP1. Le fait de mettre en œuvre plusieurs savoirs pour arriver à une étude complète d'un projet d'ouvrage d'art était plutôt intéressant. J'aurais pu passer plus de temps sur l'optimisation de la courbe de main d'œuvre pour peaufiner la dernière partie, mais je reste satisfait du travail fourni lors de cette SAÉ.",
    previewLabels: ['Note de calcul', 'Chemin de fer', 'Planning Project Libre'],
  },

  { num: '2.07', sem: 2,
    title: "Performances environnementales d'un projet de construction",
    short: "Performances environnementales d'un projet — formulation béton (Dreux-Gorisse), ACV, granulats recyclés.",
    intro: "Analyse des performances environnementales d'un projet de construction : étude de la formulation des bétons (méthode Dreux-Gorisse modifiée), évaluation de leur impact carbone via des outils dédiés, comparaison de solutions avec granulats recyclés. Deux TP matériaux (paramètres d'état, résistance du béton) intégrés dans un rapport environnemental complet, soutenu devant jury.",
    competences: [
      { code: 'AC1.1.1', level: 3 },
      { code: 'AC1.6',   level: 3 },
    ],
    livrables: [
      { name: 'Rapport environnemental SAÉ 2.07', ext: 'PDF', path: 'SAE/SAE 2.07/Rendu SAE 2.07 - Jules LE GARS Briac RAULT et Angele BERNARD.pdf' },
      { name: 'Annexe 1 — TP paramètres d\'état', ext: 'PDF', path: "SAE/SAE 2.07/ANNEXE 1 - TP PARAMETRE D'ÉTAT.pdf" },
      { name: 'Annexe 2 — TP résistance béton', ext: 'PDF', path: 'SAE/SAE 2.07/ANNEXE 2 - TP BÉTON.pdf' },
    ],
    bilan: "Cette SAÉ était un défi dans son organisation puisqu'elle comptait sur l'autonomie des étudiants. Je pense avoir répondu aux différents attendus avec mon groupe lors de la soutenance. Les différents TP étaient une bonne synthèse des matières MX2 et MX3 concernant les matériaux, mais aussi des cours portant sur l'ACV des structures dispensés plus tôt dans l'année.",
    previewLabels: ['Formulation béton', 'Analyse ACV', 'Rapport enviro.'],
  },

  // — Semestre 3 ——————————————————————————————————
  { num: '3.01', sem: 3,
    title: "Conception architecturale BIM — Le Tohannic",
    short: "Conception architecturale BIM d'une maison individuelle R+1 sous Revit — plans de niveaux, façades, vues 3D.",
    intro: "Conception architecturale complète d'une maison individuelle R+1 (Le Tohannic, programme DARYS Habitat) sous Revit Architecture. Dossier de production graphique solo comprenant les plans de tous niveaux cotés, les élévations des quatre façades et des vues 3D rendues — avec charte graphique propre (Atelier Le Gars).",
    competences: [
      { code: 'AC1.7',   level: 3 },
      { code: 'AC1.1.3', level: 3 },
    ],
    livrables: [
      { name: 'Plans de niveaux — Le Tohannic', ext: 'PDF', path: 'SAE/SAE 3.01/1 - Projet Thoanic - Jules Le Gars.pdf' },
      { name: 'Plans de façades — Le Tohannic', ext: 'PDF', path: 'SAE/SAE 3.01/2 - Projet Thoanic - Jules Le Gars.pdf' },
      { name: 'Dossier complet', ext: 'PDF', path: 'SAE/SAE 3.01/Projet Thoanic - Jules Le Gars.pdf' },
    ],
    bilan: "Ce projet de conception solo m'a permis d'investir pleinement Revit pour produire un dossier de maison individuelle complet. J'ai apprécié la liberté créative offerte, en particulier la cohérence entre le dessin 2D, le modèle 3D et la charte graphique de mon agence fictive. Travailler seul de A à Z sur un projet de conception est une expérience formatrice qui prépare bien aux missions en bureau d'études.",
    previewLabels: ['Plans de niveaux', 'Façades', 'Vues 3D Revit'],
  },

  { num: '3.03', sem: 3,
    title: "Dimensionnement d'ossature légère — hangar bois & métal",
    short: "Dimensionnement ELU/ELS d'un hangar en deux filières : ossature métallique et ossature bois (Eurocodes).",
    intro: "Dimensionnement ELU et ELS d'un hangar industriel selon deux filières constructives parallèles : construction métallique (pannes, arbalétriers et poteaux IPE) et construction bois (pannes, arbalétriers et poteaux GL). Descentes de charges neige, vent et charges permanentes selon les Eurocodes, pour une implantation à Riaillé (44440, altitude 25 m NGF). Travail réalisé en binôme avec Briac Rault.",
    competences: [
      { code: 'AC3.1.1', level: 3 },
      { code: 'AC3.3',   level: 3 },
    ],
    livrables: [
      { name: 'Synthèse des hypothèses — ossature légère', ext: 'PDF', path: 'SAE/SAE 3.03/SAÉ 3.03 - Jules LE GARS et Briac RAULT.pdf' },
    ],
    bilan: "Cette SAÉ m'a demandé de dimensionner simultanément deux ossatures légères — métallique et bois — pour un hangar identique. Travailler avec les Eurocodes dans les deux matériaux en parallèle a mis en évidence leurs logiques propres : combinaisons d'actions, vérification ELU/ELS, sections disponibles. Un exercice dense qui prépare directement au travail en bureau d'études structure.",
    previewLabels: ['Ossature métal', 'Ossature bois', 'Note de calcul'],
  },

  { num: '3.04', sem: 3,
    title: "Analyse thermique d'une maison individuelle",
    short: "Bilan thermique complet d'une maison individuelle — déperditions, Pléiades, dimensionnement des chauffages.",
    intro: "Bilan thermique complet d'une maison individuelle R+1 de 133 m² située à La Roche-sur-Foron (zone climatique H1c, altitude 600 m) : calcul des déperditions par l'enveloppe, ponts thermiques et renouvellement d'air, dimensionnement des émetteurs de chaleur (plancher chauffant RdC en régime 45/40/19, radiateurs étage), vérification et analyse via Pléiades. Réalisé en binôme avec Briac Rault.",
    competences: [
      { code: 'AC1.5', level: 3 },
    ],
    livrables: [
      { name: 'Analyse thermique — note de calcul', ext: 'PDF', path: 'SAE/SAE 3.04/SAÉ 3.04 - Jules Le Gars et Briac Rault (note de calcul).pdf' },
      { name: 'Feuilles de calcul thermique', ext: 'XLSX', path: 'SAE/SAE 3.04/SAÉ 3.04 - Jules Le Gars et Briac Rault.xlsx' },
    ],
    bilan: "Cette SAÉ m'a conduit à réaliser un bilan thermique complet, du calcul des déperditions jusqu'au dimensionnement précis des émetteurs de chaleur. L'utilisation de Pléiades pour la simulation a permis de vérifier et d'affiner les calculs manuels. Un travail qui mobilise à la fois la physique du bâtiment, la réglementation RE2020 et le dimensionnement des systèmes.",
    previewLabels: ['Déperditions', 'Pléiades', 'Dimensionnement chauffage'],
  },

  { num: '3.06', sem: 3,
    title: "Diagnostic complet d'un ouvrage existant",
    short: "Rapport de diagnostic complet (DPE, amiante, plomb, électricité, acoustique, pathologies) d'un immeuble.",
    intro: "Rapport de diagnostic complet d'un immeuble de logements à Saint-Nazaire, réalisé sous couverture du bureau d'études fictif GALAR Diagnostic. Volets couverts : Loi Carrez, DPE, installation électrique, amiante, plomb, termites, risques naturels et technologiques, acoustique, ventilation, pathologies du clos couvert. Chaque volet mobilise une réglementation et une méthodologie spécifiques. Binôme Jules LE GARS & Briac RAULT.",
    competences: [
      { code: 'AC6.1',   level: 3 },
      { code: 'AC6.1.b', level: 3 },
      { code: 'AC6.2',   level: 3 },
    ],
    livrables: [
      { name: 'Rapport de diagnostic SAÉ 3.06', ext: 'PDF', path: 'SAE/SAE 3.06/SAÉ 3.06 - Jules LE GARS et Briac RAULT - Vfinale.pdf' },
    ],
    bilan: "Ce rapport de diagnostic est ma SAÉ la plus complète en volume : DPE, amiante, plomb, termites, électricité, acoustique, pathologies du clos couvert — chaque volet mobilise une réglementation et une méthodologie spécifiques. Travailler en binôme sous couverture d'un bureau d'études fictif a renforcé la rigueur du formalisme adopté. Une SAÉ qui m'a directement nourri dans mon travail de diagnostic chez SIXENSE.",
    previewLabels: ['DPE & diagnostic', 'Pathologies', 'Rapport GALAR'],
  },

  // — Semestre 4 (placeholders) ——————————————————————————————————
  { num: '4.01', sem: 4, title: "SAÉ 4.01 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ est en cours. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: 'Livrable — à venir', ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.02', sem: 4, title: "SAÉ 4.02 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ est en cours. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: 'Livrable — à venir', ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.03', sem: 4, title: "SAÉ 4.03 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ est en cours. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: 'Livrable — à venir', ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.04', sem: 4, title: "SAÉ 4.04 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ est en cours. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: 'Livrable — à venir', ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.05', sem: 4, title: "SAÉ 4.05 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ est en cours. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: 'Livrable — à venir', ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
  { num: '4.06', sem: 4, title: "SAÉ 4.06 — à venir",
    short: "Contenu à venir pour cette SAÉ du semestre 4.",
    intro: "Cette SAÉ est en cours. Le contenu sera ajouté en fin de semestre.",
    competences: [{ code: 'AC1.1.1', level: 2 }],
    livrables: [{ name: 'Livrable — à venir', ext: 'PDF' }],
    bilan: "Bilan à compléter.",
    previewLabels: ['À venir', '—', '—'] },
];

const COMPANY_PHOTOS = [
  { src: 'assets/carousel-2.jpg', caption: "Accès auscultation — sous tablier" },
  { src: 'assets/carousel-3.jpg', caption: "Inspection détaillée — pont sur la Loire" },
  { src: 'assets/carousel-4.jpg', caption: "Sous-face de tablier — ouvrage routier" },
  { src: 'assets/carousel-5.jpg', caption: "Nacelle d'inspection — équipe SIXENSE" },
  { src: 'assets/carousel-9.jpg', caption: "Engin de visite Barin — déploiement matinal" },
  { src: 'assets/carousel-6.jpg', caption: "Auscultation visuelle — relevé de pathologies" },
  { src: 'assets/carousel-7.jpg', caption: "Inspection d'un viaduc à poutres" },
  { src: 'assets/carousel-8.jpg', caption: "Pont jumeau — circulation maintenue" },
  { src: 'assets/carousel-1.jpg', caption: "Convoi d'inspection en place sur tablier" },
];

Object.assign(window, {
  NAV_SECTIONS, ETUDES, EXPERIENCES, SAE, COMPETENCES_LIB, COMPANY_PHOTOS,
});
